name: 'SAMPLE-ACTION' #TODO: Set the name of the action
description: 'Gets version information from a .csproj file.'
inputs:
  nuget-package-name:
    description: 'The full name of the nuget package.  NOTE: Not case sensitive'
    required: true
  version:
    description: |
      The version to check for.  If the 'fail-if-version-exists' is set to true,
      then the action will fail of the version exists for the nuget package.
      The output 'version-exists' will be set to true if the version does exist
      and false if it does not.
    required: true
  fail-if-version-exists:
    description: 'If true will fail if the nuget package version exists.'
    required: false
outputs:
  version-exists: # True of false value
    description: 'The value of "true" or "false" if the version for the "version" exists.'
runs:
  using: 'node12'
  main: 'dist/index.js'