name: 'Nuget Exists Checker'
description: 'Checks if a nuget package exists in the nuget.org public repository.'
author: 'Calvin Wilkinson (KinsonDigital)'
branding:
  icon: settings
  color: purple
inputs:
  message:
    description: 'Prints a message to the console.'
    required: true

outputs:
  nuget-exists:
    description: 'True if the nuget package exists.'

# These are the arguments that are passed into the console app
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--message'
  - ${{ inputs.message }}
