name: Github Action Test

on:
  workflow_dispatch:

jobs:
  Test_GitHub_Action:
    name: Test GitHub Action
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check For Nuget Package
      id: nuget-check
      uses: KinsonDigital/NugetVersionChecker@v0.1.0
      with:
        nuget-package-name: KinsonDigital.CASL
        version: 1.0.0-preview.77
        fail-if-version-exists: true

    - name: Display Action Output
      run: Write-Host 'NugetVersionChecker Result --> ${{ steps.nuget-check.outputs.version-exists }}'
